version: '3.9'

services:
  backend:
    build:
      context: ./src-tauri/backend
      dockerfile: Dockerfile
    container_name: echo-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: echo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

# Para produção, adicione volumes/persistência conforme necessário
